# generated by datamodel-codegen:
#   filename:  jsonresume_schema.json
#   timestamp: 2025-04-14T15:15:58+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class Location(BaseModel):
    city: str = Field(..., examples=['Lachine'], title='The city Schema')
    region: str = Field(..., examples=['Quebec'], title='The region Schema')
    address: str = Field(
        ..., examples=['123, 2nd Avenue Lachine'], title='The address Schema'
    )
    postalcode: str = Field(..., examples=['H8T 2H7'], title='The postalcode Schema')
    countrycode: str = Field(..., examples=['Canada'], title='The countrycode Schema')


class Profile(BaseModel):
    network: str = Field(..., examples=['Linkedin'], title='The network Schema')
    username: str = Field(..., examples=[None], title='The username Schema')


class Basics(BaseModel):
    name: str = Field(..., examples=['John Doe'], title='The name Schema')
    email: str = Field(..., examples=['john_doe@gmail.com'], title='The email Schema')
    label: str = Field(
        ..., examples=['Manager - Donations & Sponsorships'], title='The label Schema'
    )
    phone: str = Field(..., examples=['514260-6137'], title='The phone Schema')
    summary: str = Field(
        ...,
        examples=[
            'Experienced marketing brand manager who has worked for global leaders in the aviation industry. Managed the strategic planning and budget for brand awareness activities on an international scale. Organized events of varying sizes that targeted both internal and external customers. Developed traditional advertising and digital marketing campaigns in support of brand strategy. Collaborated effectively with marketing, sales, and other teams to achieve corporate objectives. Optimized sponsorship opportunities by continuously seeking out promotional initiatives. Managed agency and vendor relationships. Created management tools, dashboards, and performance indicators (KPIs) . Delivered numerous projects by demonstrating innovative project management and problem-solving skills, creativity, and the ability to meet tight deadlines while maintaining respectful and professional relationships.'
        ],
        title='The summary Schema',
    )
    location: Location = Field(
        ...,
        examples=[
            {
                'city': 'Lachine',
                'region': 'Quebec',
                'address': '123, 2nd Avenue Lachine',
                'postalcode': 'H8T 2H7',
                'countrycode': 'Canada',
            }
        ],
        title='The location Schema',
    )
    profiles: List[Profile] = Field(
        ...,
        examples=[[{'network': 'Linkedin', 'username': None}]],
        title='The profiles Schema',
    )


class WorkItem(BaseModel):
    name: str = Field(..., examples=['ICT Infracon'], title='The name Schema')
    enddate: str = Field(..., examples=['2018-02-15'], title='The enddate Schema')
    summary: str = Field(..., examples=[None], title='The summary Schema')
    location: str = Field(..., examples=['Ahmedabad'], title='The location Schema')
    position: str = Field(
        ..., examples=['Assistant Software Engineer'], title='The position Schema'
    )
    startdate: str = Field(..., examples=['2017-06-15'], title='The startdate Schema')
    highlights: List[str] = Field(
        ...,
        examples=[
            [
                'Demonstrated expertise in Core JAVA, Spring Boot, and Hibernate frameworks, leading to a 20% increase in application efficiency',
                'Optimized the database operations in Oracle by 5% in time complexity and performed PL/SQL features',
            ]
        ],
        title='The highlights Schema',
    )
    description: str = Field(..., examples=[None], title='The description Schema')


class EducationItem(BaseModel):
    area: str = Field(
        ...,
        examples=[
            'Business Analytics and Information Systems(Computer Science/ Computer Engineering)'
        ],
        title='The area Schema',
    )
    score: str = Field(..., examples=[None], title='The score Schema')
    courses: List = Field(..., examples=[[]], title='The courses Schema')
    enddate: str = Field(..., examples=['Fri Dec 01 2023'], title='The enddate Schema')
    startdate: str = Field(..., examples=[None], title='The startdate Schema')
    studytype: str = Field(
        ..., examples=['Master of Science'], title='The studytype Schema'
    )
    institution: str = Field(
        ..., examples=['University of South Florida'], title='The institution Schema'
    )


class VolunteerItem(BaseModel):
    enddate: str = Field(..., examples=['2021-09-15'], title='The enddate Schema')
    summary: str = Field(
        ...,
        examples=[
            'Completed administrative functions included volunteering management, outreach, and records management.'
        ],
        title='The summary Schema',
    )
    position: str = Field(
        ..., examples=['Disaster Response Admin'], title='The position Schema'
    )
    startdate: str = Field(..., examples=['2020-09-15'], title='The startdate Schema')
    highlights: List = Field(..., examples=[[]], title='The highlights Schema')
    organization: str = Field(
        ..., examples=['American Red Cross'], title='The organization Schema'
    )


class Award(BaseModel):
    date: str = Field(..., examples=['2024-05-03'], title='The date Schema')
    title: str = Field(
        ...,
        examples=["Dean's Award for Scholastic Excellence"],
        title='The title Schema',
    )
    awarder: str = Field(..., examples=['Sulin Ba'], title='The awarder Schema')
    summary: str = Field(..., examples=[None], title='The summary Schema')


class Certificate(BaseModel):
    date: str = Field(..., examples=[None], title='The date Schema')
    name: str = Field(..., examples=['SAFe Agilist (SA)'], title='The name Schema')
    issuer: str = Field(..., examples=['SAFe Agilist'], title='The issuer Schema')


class Publication(BaseModel):
    name: str = Field(..., examples=['Diving Deeper'], title='The name Schema')
    summary: str = Field(..., examples=[None], title='The summary Schema')
    publisher: str = Field(
        ...,
        examples=['Oregon State University, Geospatial Ecology of Maine Megafauna Lab'],
        title='The publisher Schema',
    )
    releasedate: str = Field(..., examples=[None], title='The releasedate Schema')


class Skill(BaseModel):
    name: str = Field(..., examples=['• Brand Management'], title='The name Schema')


class Language(BaseModel):
    fluency: str = Field(..., examples=['Native', 'Fluent'], title='The fluency Schema')
    language: str = Field(
        ..., examples=['English', 'Spanish'], title='The language Schema'
    )


class Interest(BaseModel):
    name: str = Field(
        ..., examples=['Hiking', 'Yoga', 'Photography'], title='The name Schema'
    )


class Reference(BaseModel):
    name: str = Field(
        ..., examples=['Eduardo Donizete', 'Denise Higgins'], title='The name Schema'
    )
    reference: str = Field(
        ...,
        examples=[
            'Computer Network Engineer\n0451 310 884\nedonizeti@gmail.com\nIT, Co-worker',
            'Office Manager\n0416 035 037\nabasketcase@bigpond.com\nMy Manager',
        ],
        title='The reference Schema',
    )


class Project(BaseModel):
    name: str = Field(
        ..., examples=['Significance of IQ in twins'], title='The name Schema'
    )
    roles: List = Field(..., examples=[[]], title='The roles Schema')
    enddate: str = Field(..., examples=['Mon May 01 2023'], title='The enddate Schema')
    startdate: str = Field(..., examples=[None], title='The startdate Schema')
    highlights: List = Field(..., examples=[[]], title='The highlights Schema')
    description: str = Field(
        ...,
        examples=[
            '•\tDeveloped a machine learning model and processed a large dataset of twins IQ and genetic score.\n•\tUsed feature selection techniques and statistical tests such as Kruskal Anova test, Shapiro test, Z score, and Chi square to identify the most relevant features for modelling.\n•\tEvaluated model performance, and compared results to existing research on the topic'
        ],
        title='The description Schema',
    )


class RootSchema(BaseModel):
    basics: Basics = Field(
        ...,
        examples=[
            {
                'name': 'John Doe',
                'email': 'john_doe@gmail.com',
                'label': 'Manager - Donations & Sponsorships',
                'phone': '514260-6137',
                'summary': 'Experienced marketing brand manager who has worked for global leaders in the aviation industry. Managed the strategic planning and budget for brand awareness activities on an international scale. Organized events of varying sizes that targeted both internal and external customers. Developed traditional advertising and digital marketing campaigns in support of brand strategy. Collaborated effectively with marketing, sales, and other teams to achieve corporate objectives. Optimized sponsorship opportunities by continuously seeking out promotional initiatives. Managed agency and vendor relationships. Created management tools, dashboards, and performance indicators (KPIs) . Delivered numerous projects by demonstrating innovative project management and problem-solving skills, creativity, and the ability to meet tight deadlines while maintaining respectful and professional relationships.',
                'location': {
                    'city': 'Lachine',
                    'region': 'Quebec',
                    'address': '123, 2nd Avenue Lachine',
                    'postalcode': 'H8T 2H7',
                    'countrycode': 'Canada',
                },
                'profiles': [{'network': 'Linkedin', 'username': None}],
            }
        ],
        title='The basics Schema',
    )
    work: List[WorkItem] = Field(
        ...,
        examples=[
            [
                {
                    'name': 'ICT Infracon',
                    'enddate': '2018-02-15',
                    'summary': None,
                    'location': 'Ahmedabad',
                    'position': 'Assistant Software Engineer',
                    'startdate': '2017-06-15',
                    'highlights': [
                        'Demonstrated expertise in Core JAVA, Spring Boot, and Hibernate frameworks, leading to a 20% increase in application efficiency',
                        'Optimized the database operations in Oracle by 5% in time complexity and performed PL/SQL features',
                    ],
                    'description': None,
                }
            ]
        ],
        title='The work Schema',
    )
    education: List[EducationItem] = Field(
        ...,
        examples=[
            [
                {
                    'area': 'Business Analytics and Information Systems(Computer Science/ Computer Engineering)',
                    'score': None,
                    'courses': [],
                    'enddate': 'Fri Dec 01 2023',
                    'startdate': None,
                    'studytype': 'Master of Science',
                    'institution': 'University of South Florida',
                }
            ]
        ],
        title='The education Schema',
    )
    volunteer: List[VolunteerItem] = Field(
        ...,
        examples=[
            [
                {
                    'enddate': '2021-09-15',
                    'summary': 'Completed administrative functions included volunteering management, outreach, and records management.',
                    'position': 'Disaster Response Admin',
                    'startdate': '2020-09-15',
                    'highlights': [],
                    'organization': 'American Red Cross',
                }
            ]
        ],
        title='The volunteer Schema',
    )
    awards: List[Award] = Field(
        ...,
        examples=[
            [
                {
                    'date': '2024-05-03',
                    'title': "Dean's Award for Scholastic Excellence",
                    'awarder': 'Sulin Ba',
                    'summary': None,
                }
            ]
        ],
        title='The awards Schema',
    )
    certificates: List[Certificate] = Field(
        ...,
        examples=[
            [{'date': None, 'name': 'SAFe Agilist (SA)', 'issuer': 'SAFe Agilist'}]
        ],
        title='The certificates Schema',
    )
    publications: List[Publication] = Field(
        ...,
        examples=[
            [
                {
                    'name': 'Diving Deeper',
                    'summary': None,
                    'publisher': 'Oregon State University, Geospatial Ecology of Maine Megafauna Lab',
                    'releasedate': None,
                }
            ]
        ],
        title='The publications Schema',
    )
    skills: List[Skill] = Field(
        ..., examples=[[{'name': '• Brand Management'}]], title='The skills Schema'
    )
    languages: List[Language] = Field(
        ...,
        examples=[
            [
                {'fluency': 'Native', 'language': 'English'},
                {'fluency': 'Fluent', 'language': 'Spanish'},
            ]
        ],
        title='The languages Schema',
    )
    interests: List[Interest] = Field(
        ...,
        examples=[[{'name': 'Hiking'}, {'name': 'Yoga'}, {'name': 'Photography'}]],
        title='The interests Schema',
    )
    references: List[Reference] = Field(
        ...,
        examples=[
            [
                {
                    'name': 'Eduardo Donizete',
                    'reference': 'Computer Network Engineer\n0451 310 884\nedonizeti@gmail.com\nIT, Co-worker',
                },
                {
                    'name': 'Denise Higgins',
                    'reference': 'Office Manager\n0416 035 037\nabasketcase@bigpond.com\nMy Manager',
                },
            ]
        ],
        title='The references Schema',
    )
    projects: List[Project] = Field(
        ...,
        examples=[
            [
                {
                    'name': 'Significance of IQ in twins',
                    'roles': [],
                    'enddate': 'Mon May 01 2023',
                    'startdate': None,
                    'highlights': [],
                    'description': '•\tDeveloped a machine learning model and processed a large dataset of twins IQ and genetic score.\n•\tUsed feature selection techniques and statistical tests such as Kruskal Anova test, Shapiro test, Z score, and Chi square to identify the most relevant features for modelling.\n•\tEvaluated model performance, and compared results to existing research on the topic',
                }
            ]
        ],
        title='The projects Schema',
    )
